### ISSUE TITLE
Switch to tailwind

### ISSUE THREAD

**Issue by zawedcvg** [zawedcvg/Silica-Ranked-Website#2]
To improve performance and also use shadcn

**Comment by Avinashshiyani** [comment]
Hey @zawedcvg I can help you to Convert This thing Into TailwindCss Component By component .

**Comment by zawedcvg** [comment]
Hey @Avinashshiyani , the issues with performance are mainly due to the long list being rendered. It's related to #3. I will be closing this issue, but let me know if you want to take that up.
